/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedInterviewNewRouteImport } from './routes/_protected/interview/new'
import { Route as ProtectedInterviewIdIndexRouteImport } from './routes/_protected/interview/$id.index'
import { Route as ProtectedInterviewIdResultsRouteImport } from './routes/_protected/interview/$id.results'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedInterviewNewRoute = ProtectedInterviewNewRouteImport.update({
  id: '/interview/new',
  path: '/interview/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInterviewIdIndexRoute =
  ProtectedInterviewIdIndexRouteImport.update({
    id: '/interview/$id/',
    path: '/interview/$id/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInterviewIdResultsRoute =
  ProtectedInterviewIdResultsRouteImport.update({
    id: '/interview/$id/results',
    path: '/interview/$id/results',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/interview/new': typeof ProtectedInterviewNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/interview/$id/results': typeof ProtectedInterviewIdResultsRoute
  '/interview/$id/': typeof ProtectedInterviewIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/interview/new': typeof ProtectedInterviewNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/interview/$id/results': typeof ProtectedInterviewIdResultsRoute
  '/interview/$id': typeof ProtectedInterviewIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/interview/new': typeof ProtectedInterviewNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/interview/$id/results': typeof ProtectedInterviewIdResultsRoute
  '/_protected/interview/$id/': typeof ProtectedInterviewIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/interview/new'
    | '/api/auth/$'
    | '/interview/$id/results'
    | '/interview/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/interview/new'
    | '/api/auth/$'
    | '/interview/$id/results'
    | '/interview/$id'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/dashboard'
    | '/_protected/interview/new'
    | '/api/auth/$'
    | '/_protected/interview/$id/results'
    | '/_protected/interview/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/interview/new': {
      id: '/_protected/interview/new'
      path: '/interview/new'
      fullPath: '/interview/new'
      preLoaderRoute: typeof ProtectedInterviewNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/interview/$id/': {
      id: '/_protected/interview/$id/'
      path: '/interview/$id'
      fullPath: '/interview/$id/'
      preLoaderRoute: typeof ProtectedInterviewIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/interview/$id/results': {
      id: '/_protected/interview/$id/results'
      path: '/interview/$id/results'
      fullPath: '/interview/$id/results'
      preLoaderRoute: typeof ProtectedInterviewIdResultsRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedInterviewNewRoute: typeof ProtectedInterviewNewRoute
  ProtectedInterviewIdResultsRoute: typeof ProtectedInterviewIdResultsRoute
  ProtectedInterviewIdIndexRoute: typeof ProtectedInterviewIdIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedInterviewNewRoute: ProtectedInterviewNewRoute,
  ProtectedInterviewIdResultsRoute: ProtectedInterviewIdResultsRoute,
  ProtectedInterviewIdIndexRoute: ProtectedInterviewIdIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
